modkey = "Mod4"
mousekey = "Mod4"
workspaces = []
tags = ["A", "B", "C", "D", "E", "F"]
layouts = [
    "LeftWiderRightStack",
    "MainAndDeck",
    "MainAndVertStack",
    "MainAndHorizontalStack",
    "GridHorizontal",
    "EvenHorizontal",
    "EvenVertical",
    "Fibonacci",
    "CenterMain",
    "CenterMainBalanced",
    "Monocle",
    "RightWiderLeftStack",
]
layout_mode = "Workspace"
scratchpad = []
disable_current_tag_swap = false
focus_behaviour = "Sloppy"
focus_new_windows = true


[[keybind]]
command = "Execute"
value = "dmenu_run -p 'Run: ' -nb '#ffb300' -nf '#000000' -sb '#333333' -sf '#FFFFFF'"
modifier = ["modkey"]
key = "p"

[[keybind]]
command = "Execute"
value = "$HOME/.config/leftwm/themes/current/rofi/launcher.sh"
modifier = ["modkey"]
key = "space"

[[keybind]]
command = "Execute"
value = "$HOME/.config/leftwm/themes/current/rofi/powermenu.sh"
modifier = ["modkey", "Shift"]
key = "p"

[[keybind]]
command = "Execute"
value = "firefox https://github.com/di-effe/"
modifier = ["modkey", "Shift"]
key = "b"

[[keybind]]
command = "Execute"
value = "thunar"
modifier = ["modkey", "Shift"]
key = "e"

[[keybind]]
command = "Execute"
value = "alacritty"
modifier = ["modkey", "Shift"]
key = "Return"

[[keybind]]
command = "CloseWindow"
modifier = ["modkey", "Shift"]
key = "q"

[[keybind]]
command = "SoftReload"
modifier = ["modkey", "Shift"]
key = "r"

[[keybind]]
command = "Execute"
value = "loginctl kill-session $XDG_SESSION_ID"
modifier = ["modkey", "Shift"]
key = "x"

[[keybind]]
command = "Execute"
value = "slock"
modifier = ["modkey", "Control"]
key = "l"

[[keybind]]
command = "MoveToLastWorkspace"
modifier = ["modkey", "Shift"]
key = "w"

[[keybind]]
command = "SwapTags"
modifier = ["modkey"]
key = "w"

[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "k"

[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "j"

[[keybind]]
command = "MoveWindowTop"
modifier = ["modkey"]
key = "Return"

[[keybind]]
command = "FocusWindowUp"
modifier = ["modkey"]
key = "k"

[[keybind]]
command = "FocusWindowDown"
modifier = ["modkey"]
key = "j"

[[keybind]]
command = "NextLayout"
modifier = ["modkey", "Control"]
key = "k"

[[keybind]]
command = "PreviousLayout"
modifier = ["modkey", "Control"]
key = "j"

[[keybind]]
command = "FocusWorkspaceNext"
modifier = ["modkey"]
key = "l"

[[keybind]]
command = "FocusWorkspacePrevious"
modifier = ["modkey"]
key = "h"

[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "Up"

[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "Down"

[[keybind]]
command = "FocusWindowUp"
modifier = ["modkey"]
key = "Up"

[[keybind]]
command = "FocusWindowDown"
modifier = ["modkey"]
key = "Down"

[[keybind]]
command = "NextLayout"
modifier = ["modkey", "Control"]
key = "Up"

[[keybind]]
command = "PreviousLayout"
modifier = ["modkey", "Control"]
key = "Down"

[[keybind]]
command = "FocusWorkspaceNext"
modifier = ["modkey"]
key = "Right"

[[keybind]]
command = "FocusWorkspacePrevious"
modifier = ["modkey"]
key = "Left"

[[keybind]]
command = "GotoTag"
value = "1"
modifier = ["modkey"]
key = "1"

[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["modkey"]
key = "2"

[[keybind]]
command = "GotoTag"
value = "3"
modifier = ["modkey"]
key = "3"

[[keybind]]
command = "GotoTag"
value = "4"
modifier = ["modkey"]
key = "4"

[[keybind]]
command = "GotoTag"
value = "5"
modifier = ["modkey"]
key = "5"

[[keybind]]
command = "GotoTag"
value = "6"
modifier = ["modkey"]
key = "6"

[[keybind]]
command = "GotoTag"
value = "7"
modifier = ["modkey"]
key = "7"

[[keybind]]
command = "GotoTag"
value = "8"
modifier = ["modkey"]
key = "8"

[[keybind]]
command = "GotoTag"
value = "9"
modifier = ["modkey"]
key = "9"

[[keybind]]
command = "MoveToTag"
value = "1"
modifier = ["modkey", "Shift"]
key = "1"

[[keybind]]
command = "MoveToTag"
value = "2"
modifier = ["modkey", "Shift"]
key = "2"

[[keybind]]
command = "MoveToTag"
value = "3"
modifier = ["modkey", "Shift"]
key = "3"

[[keybind]]
command = "MoveToTag"
value = "4"
modifier = ["modkey", "Shift"]
key = "4"

[[keybind]]
command = "MoveToTag"
value = "5"
modifier = ["modkey", "Shift"]
key = "5"

[[keybind]]
command = "MoveToTag"
value = "6"
modifier = ["modkey", "Shift"]
key = "6"

[[keybind]]
command = "MoveToTag"
value = "7"
modifier = ["modkey", "Shift"]
key = "7"

[[keybind]]
command = "MoveToTag"
value = "8"
modifier = ["modkey", "Shift"]
key = "8"

[[keybind]]
command = "MoveToTag"
value = "9"
modifier = ["modkey", "Shift"]
key = "9"

[[keybind]]
command = "IncreaseMainWidth"
value = "5"
modifier = ["modkey"]
key = "a"

[[keybind]]
command = "DecreaseMainWidth"
value = "5"
modifier = ["modkey"]
key = "x"

[[keybind]]
command = "ToggleFullScreen"
modifier = ["modkey"]
key = "f"


[[keybind]]
command = "Execute"
value = "rofi -dmenu -input /tmp/leftwm-keymap -window-title 'Keymap' -theme $HOME/.config/leftwm/themes/amber/rofi/keymap.rasi"
modifier = ["modkey", "Shift"]
key = "m"

[[keybind]]
command = "Execute"
value = "$HOME/.config/rofi/bin/menu_screenshot"
modifier = ["modkey"]
key = "s"

[[keybind]]
command = "FocusNextTag"
modifier = ["modkey", "Shift"]
key = "Right"

[[keybind]]
command = "FocusPreviousTag"
modifier = ["modkey", "Shift"]
key = "Left"
